runName: "lunarLanderNEAT"
seed: 123

# Main
targetFitness:                      300.0
populationSize:                     240
targetSpeciesSize:                  12 # The idea more or less is to have 20 species, 12 members each, 6 survivors, 6*5/2 possible parent pairs
survivalThreshold:                  0.2
elitism:                            2
stagnationThreshold:                50
evaluationEpisodes:                 3 # Lunar Lander is highly stochastic, so this helps determining who's good and who just got lucky
initializeSynapses:                 True
saveCheckpoints:                    False

# Showcase Options
showcaseOptions:
  episodes:                         10
  fps:                              60
  upscalingFactor:                  4
  filename:                         "lunarLander"
  folder:                           "videos"
  vizCornerTopLeftInPercent:        [0.05, 0.05]
  vizCornerBottomRightInPercent:    [0.95, 0.60]
  globalAlpha:                      0.8

  visualization:
    coloredObservation:             True
    positiveColor:                  [0.8, 0.749, 0, 1.0]
    neutralNeuronColor:             [0.0, 0.0, 0.0, 1.0]
    neutralSynapseColor:            [0.05, 0.05, 0.05, 1.0]
    negativeColor:                  [0.498, 0.435, 0.914, 1.0]
    gridColor:                      [0.8, 0.8, 0.8, 1.0]
    gridThickness:                  5
    synapseWidthMultiplier:         3

# Mutations
mutateChildChance:                  0.80
mutationChanceModifyWeight:         0.80
mutationChanceSynapse:              0.05
mutationChanceNeuron:               0.02
resetWeightChance:                  0.02
weightMutationScale:                0.05
percentOfWeightsToMutate:           0.10

# Rarely Modified
defaultCompatibilityThreshold:      0.8
compatibilityAdjustmentSpeed:       0.1
lossWeight_E:                       1.0
lossWeight_D:                       1.0
lossWeight_W:                       0.4